version: '3'
services:
  node:
    image: node:8.7.0-alpine
    working_dir: /code/api
    volumes:
      - "./../..:/code/api"
    command: sh -c 'yarn install && yarn dev'
    ports:
      - "${SERVICE_NODE_PORT}"

  mongodb:
    image: mongo:3.4.1
    working_dir: /data/db
    volumes:
      - mongodb_data:/data/db
    command: sh -c 'mongod --port 27017 --dbpath /data/db'
    ports:
      - "${SERVICE_MONGODB_PORT}"

volumes:
  mongodb_data:
